#!/usr/bin/env node
require('get-pixels')(process.argv[2], function(err, data) {
  var buf = new Buffer(data.data)
  var obj = {
    shape: data.shape.slice(0),
    offset: data.offset,
    stride: data.stride.slice(0),
    data: buf.toString('base64')
  }
  console.log(JSON.stringify(obj))
})
